# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

## Amazon recommends 0.2
version: 0.2

## Optional. For linux users only
# run-as: Linux-user-name

## Optional sequence. Represents information for one or more custom environment variables.
# env:
#   shell: shell-tag
#   variables:
#     key: "value"
#     key: "value"
#   parameter-store:
#     key: "value"
#     key: "value"
#   exported-variables:
#     - variable
#     - variable
#   secrets-manager:
#     key: secret-id:json-key:version-stage:version-id
#   git-credential-helper: no | yes

## Optional sequence. Used to represent settings if you run your build in an explicit proxy server. 
# proxy:
#   upload-artifacts: no | yes
#   logs: no | yes

# batch:
#   fast-fail: false | true
#   build-list:
#   build-matrix:
#   build-graph:
        
phases:
  install:
  #   run-as: Linux-user-name
  #   runtime-versions:
  #     runtime: version
  #     runtime: version
    commands:
      - npm i -g serverless
  #   finally:
  #     - command
  pre_build:
    # run-as: Linux-user-name
    commands:
      - composer install
      - npm install
    # finally:
    #   - command
    #   - command
  build:
    # run-as: Linux-user-name
    commands:
      - npm run prod      
    # finally:
    #   - command
    #   - command
  post_build:
    # run-as: Linux-user-name
    commands:
      # run unit tests

      - aws s3 sync public/assets s3://$BUCKET_NAME
      # efs stuff (figure out symlink stuff)


      # deploy this to /dev
      - php artisan cache:clear
      - serverless deploy # ignore public/assets and vendor
      # run integration tests

      # deploy to prod

    # finally:
    #   - command
    #   - command

# reports:
#   report-group-name-or-arn:
#     files:
#       - location
#       - location
#     base-directory: location
#     discard-paths: no | yes
#     file-format: report-format

## Optional sequence. Represents information about where CodeBuild can find the build output
## and how CodeBuild prepares it for uploading to the S3 output bucket. This sequence is not
## required if, for example, you are building and pushing a Docker image to Amazon ECR, or
## you are running unit tests on your source code, but not building it.
artifacts:
  files:
    - '**/*'
#     - location
#   name: artifact-name
#   discard-paths: no | yes
#   base-directory: location
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       name: secondary-artifact-name
#       discard-paths: no | yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: no | yes
#       base-directory: location

## Optional sequence. Represents information about where CodeBuild can prepare the files
## for uploading cache to an S3 cache bucket. This sequence is not required if the cache
## type of the project is No Cache.
# cache:
#   paths:
#     - path
#     - path
